# Generated by Django 2.2.2 on 2019-12-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
